# f = open("Preeti.txt","w")
# f.write("Preeti is smart and gorgeous lady.")
# f.close()
# f = open("Riya.txt","a")
# f.write("Yo! I'm on the way....\n")
# f.close()
# f = open("Riya.txt","a")
# a = f.write("Yo! I'm on the way....\n")
# print(a)
# f.close()
# f = open("Riya.txt","w")
# a = f.write("Yo! I'm on the way....\n")
# print(a)
# f.close()

# f = open("Preeti.txt","r+")
# print(f.read())
# f.write("Preeti is a software engineer.\n")

f = open("Preeti.txt","a")
write = input("Add more anything in this file\n")
f.write(write + "\n")
f.close()